version: "3.9"

services:
  web:
    container_name: web-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: npm start

  tailwindcss:
    container_name: tailwindcss-watcher
    build:
      context: .
    volumes:
      - ./app:/usr/src/app
    command: npx tailwindcss -i /usr/src/app/src/style/main.scss -o /usr/src/app/src/style/output.css -w
    restart: unless-stopped
    tty: true